### ISSUE TITLE
"Burn Speed" selection slider is not functional

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BurnItNow#10]
Selecting the burn speed using the slider does not set the burn speed - it always burns at 48X regardless (using a 52X CD-R).

**Comment by Vidrep** [comment]
Additionally the slider could be replaced by a spinner.

**Comment by Vidrep** [comment]
The slider write speed (burn rate) selection does not conform to optical disc standard.

![disc burn speeds](https://cloud.githubusercontent.com/assets/13264393/19613742/b816534e-97ab-11e6-985e-3a4267bfb23a.jpg)

**Comment by humdingerb** [comment]
The burn speed slider works in the upcoming release.
Special case for audio CDs: if the speed is 4x (recommended speed) or below, FIFO size is -fs=4m for max compatibility, otherwise it's -fs=16m for faster speeds.
Reading in CDs for cloning is currently always done at 10x. Vidrep's experiments shown that to be the sweetspot. Adding another slider would clutter the GUI and is probably more confusing than helpful.
